site_name: TJay Dev - Wiki
repo_url: https://github.com/tomajask/wiki
repo_name: tomajask/wiki
edit_uri: edit/master/docs/

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github-square
    logo: fontawesome/regular/folder-open
  palette:
    - scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: IBM Plex Mono
  features:
    - navigation.instant

plugins:
  - git-revision-date
  - search
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - admonition            # enables coloured blocks mid article
  - attr_list             # improves image handling
  - pymdownx.details      # enables collapsible admonitions
  - footnotes
  - meta                  # adds support for front matter
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.highlight:   # code highlighting
      linenums: true
  - pymdownx.tabbed       # enables tabs for embedded blocks
  - pymdownx.snippets
  - pymdownx.superfences  # allows for the nesting of code blocks inside other blocks
  - pymdownx.keys

copyright: 2021 &copy; Thomas Jaskiewicz - GPL-3.0 License
extra:
  analytics:
    provider: umami
    domain: umami.tjay.tools
    key: 06208c65-fafa-4adf-a03d-9cd1e403c7a2
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/tomajask'
      name: Thomas Jaskiewicz on GitHub
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/tomjaskiewicz'
      name: Thomas Jaskiewicz on Twitter
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/in/tomaszjaskiewicz/'
      name: Thomas Jaskiewicz on LinkedIn
    - icon: 'fontawesome/brands/dev'
      link: 'https://dev.to/tjay_dev'
      name: Thomas Jaskiewicz on Dev.to
    - icon: 'fontawesome/brands/instagram'
      link: 'https://www.instagram.com/tjay.dev'
      name: Thomas Jaskiewicz on Instagram
    - icon: 'fontawesome/solid/ghost'
      link: 'https://tjay.dev'
      name: Dev Blog by Thomas Jaskiewicz
    - icon: 'fontawesome/solid/external-link-square-alt'
      link: 'https://links.tjay.dev'
      name: All links to Thomas' websites
